### ISSUE TITLE
Prepare some vocab YAML files

### ISSUE THREAD

**Issue by agstephens** [cedadev/search-futures#130]
- [x] @rhysrevans3 provide a YAML template for Ag to populate with CMIP5 and CMIP6 vocabs
- [x] @agstephens: populate those YAML files

**Comment by rhysrevans3** [comment]
I've just checked the code and it looks like it's not yet using YAML but I believe it should look something like this for the cache creation where each workflow is a different namespace:
```
workflows:
  cmip6:
    concept_schemes:
      - name: source_id
        prefLabel: source_id
        altLabel: Source ID
        location: ../../CMIP6_source_id.json
      - name: source_type
        prefLabel: source_type
        altLabel: Source Type
        location: ../../CMIP6_source_type.json
```

and this for the `general` vocab:
```
concept_schemes:
  - name: model
    prefLabel: model
    description: A model is a ...
    sub_schemes:
      - name: source_id
        namespace: 'http://test.org/cmip6/'
      - name: model
        namespace: 'http://test.org/cmip5/'
```
